### ISSUE TITLE
Error parsing file ... not a constructor

### ISSUE THREAD

**Issue by dougalx** [adamjimenez/shiftedit#309] opened 2018-05-25 14:57 UTC
Upon saving a JS file to an FTP server:

`Error parsing file: (intermediate value)(intermediate value)(intermediate value) is not a constructor`

I just saved this file a few times and it worked fine, but then I get this message and can't upload unless I refresh ShiftEdit

**Comment by adamjimenez** [comment] 2018-09-04 20:42
Is it reproducible?
Likely to be code dependent..

**Comment by adamjimenez** [comment] 2020-08-19 13:02
I need steps to reproduce this. Closing.

**Closed by adamjimenez** 2020-08-19 13:02 UTC

**Comment by adamjimenez** [comment] 2020-08-19 13:09
dupe of #304
