### ISSUE TITLE
Suggestion: Customizable keyboard shortcuts.

### ISSUE THREAD

**Issue by mpmw** [adamjimenez/shiftedit#203] opened 2016-10-04 17:13 UTC
Unfortunately, many of the significant keyboard shortcuts (e.g., moving lines, even displaying the keyboard shortcut window itself, etc.) are incompatible with the key equivalents in Chrome OS. Those who develop in Chrome OS (yours truly, for example) are more likely to use ShiftEdit, given the limited selections of code editors available for the environment.

Suggestion: Offer customizable or OS/browser-specific shortcuts. If the former, a file vs. UI approach would -definitely suffice.

**Comment by adamjimenez** [comment] 2016-10-06 20:59
I've pushed an update to the dev channel that has a GUI implementation for choosing keyboard bindings.
I went with a GUI because it's nicer to use and easier to convey which keys are reserved by the browser/ OS.
In the latest update you can set bindings from Help -> Shortcuts (I may move this under edit menu).
Please check it out and provide feedback.
I need to add more shortcuts, please let me know the ones you want the most and I'll do them next.

**Comment by mpmw** [comment] 2016-10-07 00:43
That's fantastic. I'll check it out when I get back to work tomorrow.

**Comment by mpmw** [comment] 2016-10-07 05:35
I gave it a try. I really like that the menus are updated with the
assignments. It's surprising how many programs don't do that.

I wanted to set up Ctrl-Alt-Up and Ctrl-Alt-Down as an alternative for
moving lines. Left and Right arrows could be assigned, but not the Up and
Down. For the feedback, it would be nice if the assigned key lit up on
keydown and the on-screen keyboard closed on keyup. It's a bit less jarring.

It's surprising what keys are used by Chrome OS. For instance, Ctrl+/ shows
their Help. Shift-Esc is their Task Manager. Since I am constantly using
the Find feature, I'd love to replace Ctrl-\ with Esc. By the way, I still
like the idea of having a single-line panel or a single-line popup for
searching. I use the feature extensively with the same pattern: Ctrl-F,
enter string, followed by Ctrl-K or Shift-Ctrl-K. It's nice to keep my
context especially since I very rarely use any of the extended search
functions.

Back to the shortcuts, rather than having a large list of buttons, perhaps
it makes more sense to use a modifier with the existing menus? For
instance, a user could Ctrl- or Shift-click on a menu item to bring up the
keyboard. It saves you from having a huge list which ultimately might to be
categorized, it's more direct for the user, it removes the question of
where the function would live (e.g., in the Edit or Help menu), and it
allows the current all-encompassing list to remain working as is. When Ctrl
or Shift are pressed menu items that cannot be customized would dim.






<http://LucidQuotes.com>

**Comment by adamjimenez** [comment] 2016-10-07 12:52
Ctrl-Alt-Up and Ctrl-Alt-Down rotate the screen in Windows so I will mark them as reserved.

I prefer the huge list of buttons because they are all in one place and there may be some buttons that aren't in the menus. In fact I might take them out of the menus now that they are in the shortcuts dialog. I may categories them as we add more.

I've moved the keybindings dialog to Edit -> Keyboard Bindings

When in the find panel. Escape will return to the code.
Setting the "Find Panel" shortcut to "Clear" will revert to the editors built-in find component which you may prefer.

**Comment by mpmw** [comment] 2016-10-07 17:35
Okay, I switched to using Ctrl-Left and Right. I do think, though, that in
the future it would be nice for a user of one OS not to be affected by
another OS.

I hear you on the list. My one suggestion then, would be to dim the Default
button if the key assignment already is the default.

I don't think I'm seeing what you want on Find. Esc isn't returning me to
the code, and when Find is cleared, pressing Ctrl-F produces no result.




<http://LucidQuotes.com>

**Comment by adamjimenez** [comment] 2016-10-07 17:43
There wasn't a restriction to stop those shortcuts previously so I think it would be a chromeos issue as well.

Some indicator as to what is default would be handy.

re find, make sure you are on: 18.1.1

**Comment by mpmw** [comment] 2016-10-07 17:50
I just realized the issue with accessing the default Find function. The
Chrome browser responds to keyboard equivalents based on where the focus
is. For example, if I am in the address bar, and I press Shift-Ctrl-B, the
bookmark bar toggles. Likewise, if I am in ShiftEdit's left-side control
panel, Shift-Ctrl-B also toggles the bookmark bar. However, if the cursor
is the code window, Shift-Ctrl-B has no effect. Ctrl-F is the same. It only
displays the browser's default Find function if the focus is not in the
code window.




<http://LucidQuotes.com>

**Comment by mpmw** [comment] 2016-10-07 17:55
I definitely am on version 18.1.1.

Esc doesn't close the Find panel no matter the location of the input focus.
I have written sites that grab the Esc key event, so I'm pretty certain
it's not a Chrome issue.

I appreciate the effort to make Esc work, but if I can get to the default
find function (as discussed in the previous communication), then that would
definitely work, and I'll continue using Ctrl-| (or another shortcut when
it's set-able) for the ShiftEdit find function.





<http://LucidQuotes.com>

**Comment by adamjimenez** [comment] 2016-10-07 18:02
>  It only
> displays the browser's default Find function if the focus is not in the
> code window.

This is by design as there are sometimes when using the browser search is handy like when looking for something in preferences.

> Esc doesn't close the Find panel no matter the location of the input focus.

It won't close it, it just puts the cursor back in the code editor.
Something is up with the default find - I will fix that.

**Comment by mpmw** [comment] 2016-10-07 18:05
Gotcha. Just tried it. Esc works as you said.



<http://LucidQuotes.com>

**Comment by adamjimenez** [comment] 2016-10-07 18:51
I've pushed 18.1.4 which fixes the default find facility.

**Comment by mpmw** [comment] 2016-10-07 18:55
Works perfectly. Thank you. Now I can use Ctrl-F for simple finds, and
Shift-Ctrl-F to use ShiftEdit's. Thanks again.





<http://LucidQuotes.com>

**Closed** 2016-10-19 10:37 UTC
